### ISSUE TITLE
-g选项图形界面显示错误

### ISSUE THREAD

**Issue by kuankuanlv** [bit4woo/passmaker#4]
右边的按钮没有文字
![image](https://user-images.githubusercontent.com/19601210/49700523-ab69ff80-fc1a-11e8-9927-bfcb3e24d5f0.png)

**Comment by bit4woo** [comment]
看你的问题似乎和你使用了MAC系统有关，抱歉目前没有环境进行测试

**Comment by bit4woo** [comment]
已适配mac环境
